[package]
name = "reqex"
version = "0.1.0"
authors = ["reqty"]
edition = "2018"

[profile.release]
lto = "thin"
panic = "abort"

[dependencies]
futures = "0.3"
tokio = { version = "0", features = [ "macros" ] }
telegram-bot = "0.7"
regex = "1"
